[data]
rurl = "write result portal url here"
hurl = "write main home page url here"

hostname = "localhost" #mostly localhost for database connection, change if different
username = "write your database username here"
dbpsw = "write your database password here"
dbname = "write your database name here"

email_host = "write your email hostname here" #usually your domain name 
email_psw = "writ your website email password here"
email_user ="write your email username here" # e.g info@yourdomain.com
email_sender = "write your website name here" # e.g NewAge Academy
smtp_port = 465 #change if different


# leave this block unchanged
dirgen = "Director General"
manager = "School Manager"
asstmanager = "Asst. School Manager"
ictdir = "ICT Director"
asstictdir = "Asst. ICT Director"
principal =  "Principal"
secretary = "Secretary"
accountant = "Accountant"
exam_officer = "Exam Officer"
asst_exam_officer = "Asst. Exam Officer"


site = "write site name here, it will display on the site"
site2 ="Alternative site name"
# set both site and site2 to the same value if you don't have an Alternative name such as an abbreviation or accronyms
siteEmail = "write default customer support or enquiry email here"
schoolAddress = "write the physical address of the school or organistion here"
backupToken = "backupToken, this value should be defined as a constant inside /backup/config.php"